language: python
python: "2.7"
env:
  - DB=sqlite
  - DB=postgres
install:
  - if [ $DB = 'postgres' ]; then psql -c 'create database kingdoms;' -U postgres; fi
  - if [ $DB = 'sqlite' ]; then sed -i '/psycopg2/d' requirements.txt; fi
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls --use-mirrors
script: 
  coverage run manage.py test kingdom mission title internal event bargain reporting
after_success:
  coveralls
