language: python
python: "2.7"
env:
  - DB=sqlite
  - DB=postgres
install:
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database kingdoms;' -U postgres; fi"
  -  sh -c "if [ '$DB' = 'sqlite' ]; then sed '/psycopg2/d' requirements.txt > requirements.txt"
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls --use-mirrors
script: 
  coverage run manage.py test kingdom mission title internal event bargain reporting
after_success:
  coveralls
