language: python
python:
  - "2.7"
  - "pypy"
env:
  - DB=sqlite
  - DB=postgres
install:
  - "pip install -r requirements.txt"
  - "./manage.py syncdb --noinput"
  - "./manage.py migrate"
script: "./manage.py test kingdom mission title internal event"