language: python
python: "2.7"
env:
  - DB=sqlite
  - DB=postgres
install:
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS myapp_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database myapp_test;' -U postgres; fi"
  - "pip install -r requirements.txt"
  - "./manage.py syncdb --noinput"
  - "./manage.py migrate"
script: "./manage.py test kingdom mission title internal event"